### ISSUE TITLE
Checklist before release 1.5.0

### ISSUE THREAD

**Issue by htdat** [htdat/woo-viet#79]
https://github.com/htdat/woo-viet/wiki

# Check-list for a new release 

## Version:

- [x] File readme.txt: `Stable tag`, `Tested up to` (WP Core version).
- [x] The main file of the plugin: `Version`, `WC tested up to`.

## Changelog

- [x] Include the date of the new release
- [x] File readme.md - https://github.com/htdat/woo-viet#changelog

## Features and Roadmaps: 

- [x] File readme.txt

## Warnings (Upgrade Notice)

- [x] File readme.txt. 

## Release

- [x] Release on GitHub https://github.com/htdat/woo-viet/releases/tag/1.5.0
- [x] Release on WordPress.org `Committed revision 2379525`.

## Translation 

- [x] Link: https://translate.wordpress.org/locale/vi/default/wp-plugins/woo-viet

**Comment by htdat** [comment]
# Hot fix 1.5.1

# Check-list for a new release 

## Version:

- [ ] File readme.txt: `Stable tag`, `Tested up to` (WP Core version).
- [ ] The main file of the plugin: `Version`, `WC tested up to`.

## Changelog

- [ ] Include the date of the new release
- [ ] File readme.md - https://github.com/htdat/woo-viet#changelog

## Features and Roadmaps: 

- [ ] File readme.txt

## Warnings (Upgrade Notice)

- [ ] File readme.txt. 

## Release

- [ ] Release on GitHub https://github.com/htdat/woo-viet/releases/tag/1.5.0
- [ ] Release on WordPress.org.


## Translation 

- [x] Link: https://translate.wordpress.org/locale/vi/default/wp-plugins/woo-viet
